export interface Project {
  id: string; // Generated by nanoid
  userEmail: string; // Key when stored
  projectName: string;
  imagesURI: string[];
}

export type ProjectCreate = Omit<Project, "id">;
